### ISSUE TITLE
Config option to open link in new window?

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-quick-tray-links#1]
Love the idea of this plugin, thanks for creating it!

I can see a very specific use of this plugin within Grav Skeletons to help newer users access specific external docs, etc. Having the option to set a link to open in a new Browser Window would be awesome, as this then leaves them in the Grav Admin while they can review the related docs.

Thanks very much,
Paul

**Comment by w00fz** [comment]
FYI GitSync has been released to support the new Admin Tray, you can now sync from anywhere in the admin :)

**Comment by paulhibbitts** [comment]
Really nice @w00fz , just updated and gave it a go👍 Thanks!

**Comment by jimblue** [comment]
Agree cool be nice to add `target:_blank` to link.

**Comment by vnijhuis** [comment]
added 4 pull request for the developers to get this top work. Only the admin plugin should have a change to. See pull request 1 from me.

**Comment by paulhibbitts** [comment]
Hi @rhukster , I see there are a series of small PR's to add the ability to open Quick Links URLs in a new Browser window... any chance they might be accepted/released?🤞It would be a great enhancement!

**Comment by w00fz** [comment]
You can set a link as `external: true` and it will open in a new tab

Sorry for the extremely late reply :)
