### ISSUE TITLE
1.1.0 is not released, gpm installs 1.0.1

### ISSUE THREAD

**Issue by woutgg** [trilbymedia/grav-plugin-quick-tray-links#12]
When installing this plugin via gpm, it installs 1.0.1, which misses the very handy `external` addition.

I have installed it in a different way for now, and ran into a small issue where a single quote in the French translation ("barre d'accès") broke the admin environment. Technically I should probably file a separate issue for that, but I think it's more practial to just mention it here.

**Comment by rhukster** [comment]
1.1.0 is released now, should show up soon.
