### ISSUE TITLE
bug: error with email links

### ISSUE THREAD

**Issue by chraebsli** [trilbymedia/grav-plugin-quick-tray-links#16]
I discovered an error when I wanted to add an email link as a quick tray icon. Normally, when linking to an email address, the `href` attribute looks like this: `mailto:email@domain.tld`

But with this plugin, the `href` attribute renders to this: `/mailto:email@domain.tld`. With this, it is impossible to link an email address, since the plugin treats the URL like a path to the base URL.

I wish that there is a check if the URL refers to a [non HTTP scheme](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#href), so you can link to `tel:`, `mailto:` and much more.

**Comment by rhukster** [comment]
Actually this as related to a bug in the core of Grav -> Utils::url() method.  I have a fix in there now if you wan to test:

https://github.com/getgrav/grav/commit/ee8d783d050588aaf35261b7d1832e2bdc433fe6

**Comment by chraebsli** [comment]
Thank you! I just tested it and it works.
