### ISSUE TITLE
Quick Sidebar Links

### ISSUE THREAD

**Issue by diomed** [trilbymedia/grav-plugin-quick-tray-links#2]
How could  this be turned into Quick Sidebar Links
so it would show fully on sidebar, amongst other items
such as 
Dashboard
Configuration
Pages

etc...

**Comment by w00fz** [comment]
That's not really possible via QuickTray. Quicktray is meant only for that location as simple quick actions. What you are looking for is the `onAdminMenu` hook event from the Grav Admin Plugin, something along these lines:

```php
$this->grav['twig']->plugins_hooked_nav['Your Title'] = ['route' => 'your_route', 'icon' => 'fa-grav'];
```
